添加省市区筛选
wuhan2020/WebApp pull request #45
Opened 2020-01-31 13:21 UTC by juhaodong

修改菜单栏，并且添加省市区筛选

2020-01-31 13:28 UTC, TechQuery commented
省市区行政区 这种**基础数据**要放在一个 MobX 模型里加载、存储，不要在具体组件里重复加载

2020-01-31 14:57 UTC, juhaodong commented
> 省市区行政区 这种**基础数据**要放在一个 **MobX 模型**里加载、存储，不要在具体组件里重复加载

虽然可能没有放在mobx模型里，但是做了一定的缓存机制

2020-01-31 15:03 UTC, TechQuery requested changes
> > 省市区行政区 这种**基础数据**要放在一个 **MobX 模型**里加载、存储，不要在具体组件里重复加载
> 
> 虽然可能没有放在mobx模型里，但是做了一定的缓存机制

**基础数据**建议用单独的模型管理，如：

```typescript
import { observable } from 'mobx';

export class MetaData {
    @observable
    provinces = [];

    async loadProvinces() {
        // ...
    }
}
```

2020-01-31 15:03 UTC, TechQuery commented on source/page/Hospital/index.tsx
> +        this.initPage();
初始化操作请在 `connectedCallback()` 中执行，`render()` 方法执行可能会很频繁，给浏览器、服务器造成额外负担

2020-01-31 15:03 UTC, TechQuery commented on source/page/Hospital/index.tsx
> +        this.initProvince();
这样每次上拉加载更多都会重复加载基础数据

2020-01-31 15:35 UTC, juhaodong commented
调整了初始化代码的位置，重写了model类

2020-01-31 16:09 UTC, TechQuery approved these changes

2020-01-31 16:09 UTC, TechQuery commented on source/page/menu.ts
> +        href: 'https://github.com/wuhan2020/wuhan2020.github.io'
这个文件其他人优化过了，不要改了，回滚

2020-01-31 16:10 UTC, merged

2020-02-06 04:04 UTC, TechQuery commented
现在并没有“查看详情”…… 能再清晰地描述一下吗？或者直接提交 PR

2020-02-06 05:21 UTC, WeileiZeng commented
http://wuhan2020.org.cn/#/

不好意思，我看的是这个网站。有点蒙，那个是已经淘汰了吗？

2020-02-06 05:56 UTC, TechQuery commented
我不清楚，看不到他们的 GitHub projects、Slack channel