疫情图表性能优化 #80
wuhan2020/WebApp pull request #93
Opened 2024-08-03 09:25 UTC by ziwu7

[Add] Addition of epidemic data statistics page and chart performance optimization

2024-08-03 16:45 UTC, TechQuery requested changes

2024-08-03 16:45 UTC, TechQuery commented on source/service/Epidemic.ts
> +}
这个和上面那个函数有啥区别？

2024-08-03 16:45 UTC, TechQuery commented on source/page/index.tsx
> +
不用加这个空行。

2024-08-03 16:45 UTC, TechQuery commented on source/page/index.tsx
>  const userMenu = [
但这里需要空行。

2024-08-03 16:45 UTC, TechQuery commented on source/page/index.tsx
>  const HospitalPage = lazy(() => import('./Hospital')),
这里不需要多加一个空行，这明显是格式化脚本没有跑成功。

2024-08-03 16:45 UTC, TechQuery commented on source/page/data/menu.ts
>      }
你现在要做的实际上是对上面疫情地图里面所有图表进行重写，包括地图类型的图表。

2024-08-03 16:45 UTC, TechQuery commented on source/page/Statistics/index.tsx
> +            let city_deadCounts = cityData.map((item)=>[item.cityName,item.city_deadCount])
调接口请求数据和对数据进行预处理全放到 MobX model 那边，render 函数只放 DOM 结构对数据的引用。

2024-08-03 16:45 UTC, TechQuery commented on source/page/Statistics/index.tsx
> +    }
https://web-cell.dev/web-utility/functions/formatDate.html

2024-08-03 16:45 UTC, TechQuery commented on source/page/Statistics/index.tsx
> +import 'echarts-jsx/dist/charts/bar';
```suggestion
import {component,observer} from 'web-cell';
import 'echarts-jsx/dist/renderers/SVG';
import 'echarts-jsx/dist/components/title';
import 'echarts-jsx/dist/components/legend';
import 'echarts-jsx/dist/components/tooltip';
import 'echarts-jsx/dist/components/grid';
import 'echarts-jsx/dist/components/x-axis';
import 'echarts-jsx/dist/components/y-axis';
import 'echarts-jsx/dist/charts/line';
import 'echarts-jsx/dist/charts/bar';

import {Overall,AreaData,getOverall,getArea } from '../../service/Epidemic';
```

2024-08-27 03:03 UTC, TechQuery requested changes

2024-08-27 03:03 UTC, TechQuery commented on package.json
> +        "start": "npm run && cross-env HTTP_ENV=test  parcel source/index.html --open",
干嘛把子命令删掉，这样执行会有错的。

2024-08-27 03:03 UTC, TechQuery commented on source/page/Map/adapter/isaaclin.ts
> +        const t = roundTime(timestamp, resolution);
```suggestion
        const t = roundTime(+new Date(item.updateTime), resolution);
```
（下同）

2024-08-27 03:03 UTC, TechQuery commented on source/page/Map/component/VirusChart.tsx
> +    transformData(orderedCountryData: any[]) {
类型写清楚

2024-08-27 03:03 UTC, TechQuery commented on source/service/Epidemic.ts
> +    Record<`${'city_' | 'province_'}zipCode`,string>{}
```suggestion
export Area = 'city' | 'continent' | 'country' | 'province';

export type AreaData = Base &
    Partial<Record<`${'city' | 'province'}_${StatisticType}Count`, number>> &
    Record<`${Area}EnglishName`, string> &
    Record<`${Area}Name`, string> &
    Record<`${'city' | 'province'}_zipCode`, string>;
```

2024-08-27 03:03 UTC, TechQuery commented on source/service/Epidemic.ts
> +    for (const item of body) {
```suggestion
    const { body } = await epidemic.get<AreaData[]>('Area', { Range: '0-199' });

    for (const item of body) {
```

2024-08-29 12:23 UTC, TechQuery requested changes

2024-08-29 12:23 UTC, TechQuery commented on package.json
> +        "start": "npm run clean  && cross-env HTTP_ENV=test  parcel source/index.html --open",
无需变更

2024-08-29 12:23 UTC, TechQuery commented on package.json
>          "clean": "rm -rf .parcel-cache/ dist/",
```suggestion
         "clean": "rimraf .parcel-cache/ dist/",
```
并且执行：

```shell
pnpm i rimraf -D
```

2024-08-29 12:23 UTC, TechQuery commented on source/page/Map/adapter/isaaclin.ts
>          const prov = convertProvince(item);
单一空行无需删除

2024-08-29 12:23 UTC, TechQuery commented on source/page/Map/adapter/isaaclin.ts
> +        })
```suggestion
        source.map(item => [roundTime(+new Date(item.updateTime), resolution), item])
```

2024-08-29 12:23 UTC, TechQuery commented on source/service/Epidemic.ts
> +    const { body } = await epidemic.get<AreaData[]>('Area', { Range: '0-199' }); //
```suggestion
    const { body } = await epidemic.get<AreaData[]>('Area', { Range: '0-199' });
```

2024-08-29 12:23 UTC, TechQuery commented on source/service/Epidemic.ts
> +    return body as unknown as Province[];
改为 `.map()`

2024-08-29 16:21 UTC, TechQuery requested changes

2024-08-29 16:21 UTC, TechQuery commented on source/service/Epidemic.ts
> +    });
你这是拿 `map` 当 `forEach` 用……

2024-09-04 18:49 UTC, TechQuery requested changes

2024-09-04 18:49 UTC, TechQuery commented on source/service/Epidemic.ts
> +    return updatedBody as unknown as Province[];
```suggestion
    const updatedBody = body.map(item => ({
        provinceShortName: item.provinceName,
        confirmedCount: item.province_confirmedCount,
        suspectedCount: item.province_suspectedCount,
        curedCount: item.province_curedCount,
        deadCount: item.province_deadCount
    }));
    return updatedBody as Province[];
```
`map()` 在数学上是一个集合到另一个集合的**映射**，目标数据结构上没有的字段，硬加上能不类型报错吗？

2024-09-05 01:29 UTC, ziwu7 commented on source/service/Epidemic.ts
> +    return updatedBody as unknown as Province[];
已修正，加入Province类型包含的字段
 id: item.id,
 updateTime: item.updateTime,

2024-09-05 02:19 UTC, TechQuery approved these changes

2024-09-05 02:21 UTC, merged