[fix]Fix map json path, map data request API add range date filter condition
wuhan2020/WebApp pull request #97
Opened 2024-09-10 06:28 UTC by ziwu7

Fix map json path, map data request API add range date filter condition

2024-09-10 13:44 UTC, TechQuery requested changes

2024-09-10 13:44 UTC, TechQuery commented on source/page/Map/component/VirusMap.tsx
> +        const sortedTimeline = data.timeline.slice().sort();
```suggestion
        const sortedTimeline = [...data.timeline].sort();
```

2024-09-10 13:44 UTC, TechQuery commented on source/service/Epidemic.ts
> +        'Area?updateTime=gt.2022-01-01T10:54:11&updateTime=lt.2022-12-30T10:54:11&countryName=eq.%E4%B8%AD%E5%9B%BD'
查询参数从函数入口传入，在每次用户点击图表时再次调用查询函数并重绘。

2024-09-11 02:58 UTC, ziwu7 commented on source/service/Epidemic.ts
> +        'Area?updateTime=gt.2022-01-01T10:54:11&updateTime=lt.2022-12-30T10:54:11&countryName=eq.%E4%B8%AD%E5%9B%BD'
当前这个api数据是用于渲染地图数据的。
当前的效果是获取某段日期范围内的所有日期数据，全部日期渲染在时间轴，对应的数据渲染到地图，点击时间轴上单个日期则对应渲染数据。

新需求：查询参数从函数入口传入，在每次用户点击图表时再次调用查询函数并重绘。

实现这个需求：
1.前提得先有个全部日期的数组么，因为需要时间轴上先显示所有的日期？
2.然后点击某个日期就显示某个日期数据？这样的话全部日期数据没有全之前，左边的自动播放按钮应该就不生效了吧？

不知是否理解有误，有误的话能否提供个草图讲解下大概效果逻辑。
![image](https://github.com/user-attachments/assets/e4f4805d-8803-4b54-b2b9-49b9083a45b4)

2024-09-11 05:18 UTC, TechQuery commented on source/service/Epidemic.ts
> +        'Area?updateTime=gt.2022-01-01T10:54:11&updateTime=lt.2022-12-30T10:54:11&countryName=eq.%E4%B8%AD%E5%9B%BD'
> 实现这个需求：
> 1. 前提得先有个全部日期的数组么，因为需要时间轴上先显示所有的日期？
> 2. 然后点击某个日期就显示某个日期数据？这样的话全部日期数据没有全之前，左边的自动播放按钮应该就不生效了吧？
> 
> 不知是否理解有误，有误的话能否提供个草图讲解下大概效果逻辑。

1. 我上周例会上讲了，先人为确定一个起止时间（如 2020-01-23 武汉封城至 2023-12-01 全国放开），然后中间的日期即可用代码生成。因为整个疫情是连续时间，每次循环加一天即可。
2. 无论手动点击还是自动播放，都要写好同样的日期生成、按日期查询的逻辑。

界面设计没有变化，只是在补全逻辑和数据。

2024-09-19 07:43 UTC, TechQuery requested changes

2024-09-19 07:43 UTC, TechQuery commented on source/page/Map/component/EChartsMap.tsx
> +                const formattedDate = clickedDate.toISOString().split('T')[0]; // 格式化日期为 YYYY-MM-DD
```suggestion
                const formattedDate = formatDate(dataIndex, 'YYYY-MM-DD');
```

2024-09-19 07:43 UTC, TechQuery commented on source/page/Map/component/VirusMap.tsx
> +        return timestampArray;
```suggestion
        // 定义疫情开始和结束日期
        const startDate = +new Date('2019-12-01');
        const endDate = +new Date('2022-12-01');

        return Array.from(
            { length: (endDate - startDate) / Day + 1 },
            (_, i) => startDate + Day * i
        );
```
https://web-cell.dev/web-utility/variables/Day.html

2024-09-19 07:43 UTC, TechQuery commented on source/page/Map/component/VirusMap.tsx
> +            data: this.getTimelineData(), //[1668700800000, 1668787200000, 1668873600000], //data.timeline,
```suggestion
            data: this.getTimelineData(),
```

2024-09-19 07:43 UTC, TechQuery commented on source/service/Epidemic.ts
> +export async function getHistory(date: string = '2022-09-01') {
```suggestion
export async function getHistory(date = '2022-09-01') {
```

2024-09-19 07:43 UTC, TechQuery commented on source/page/Map/component/EChartsMap.tsx
> +    updateChartData(newData) {
```suggestion
    updateChartData(newData: Province[]) {
```

2024-09-19 07:43 UTC, TechQuery commented on source/service/Epidemic.ts
> +        `Area?updateTime=gt.${startOfDay}&updateTime=lt.${endOfDay}&countryName=eq.中国&limit=299`
```suggestion
        `Area?${new URLSearchParams([
            ['updateTime', `gt.${startOfDay}`],
            ['updateTime', `lt.${endOfDay}`],
            ['countryName', 'eq.中国'],
            ['limit', '299']
        ])}`
```

2024-09-19 14:32 UTC, ziwu7 commented on source/page/Map/component/VirusMap.tsx
> +        return timestampArray;
如果设置日期数量太多的话，时间轴不会自适应自动隐藏，需要修改为动态滑动窗口类型的时间轴吧？

2024-09-19 15:51 UTC, TechQuery requested changes

2024-09-19 15:51 UTC, TechQuery commented on source/page/Map/component/VirusMap.tsx
> +    getTimelineData = () => {
```suggestion
    get timelineData() {
```
变成**访问器属性**就更简洁了

2024-09-19 15:53 UTC, TechQuery commented on source/page/Map/component/VirusMap.tsx
> +        return timestampArray;
> 如果设置日期数量太多的话，时间轴不会自适应自动隐藏，需要修改为动态滑动窗口类型的时间轴吧？

具体图表的情况我不太清楚，能实现效果就行。

2024-09-21 07:44 UTC, TechQuery requested changes

2024-09-21 07:44 UTC, TechQuery commented on source/page/Map/component/EChartsMap.tsx
> +import { formatDate } from 'web-utility';
```suggestion
import { EChartsOption, EChartsType, init, registerMap } from 'echarts';
import { formatDate } from 'web-utility';

import { getHistory, Province } from '../../../service/Epidemic';
import { long2short } from '../adapter';
```

2024-09-21 07:44 UTC, TechQuery commented on source/page/Map/component/EChartsMap.tsx
> +                }
```suggestion
                const newData = await getHistory(formattedDate);

                this.updateChartData(newData);
```
时间轴日期只要不超出范围，按理说应该所有数据都能正常请求到，不会有网络错误，有的话现在也会全局统一捕获并提示。

2024-09-21 09:27 UTC, TechQuery approved these changes

2024-09-21 17:04 UTC, TechQuery approved these changes

2024-09-21 17:07 UTC, merged